### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Alanaslavante** [Uintra/Uintra#1]
Hi I am having trouble installing Uintra from Visual studio, there's some internal mismatch in the dependencies, any help? or status on this?

Best regards,
Alan

**Comment by Cookzenberg** [comment]
I also get an installation error after copying the instructions in the PDF:

Could not install package 'Compent.CommandBus 1.2.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.				

I don't see this package as a standalone in Nuget so not sure how to investigate.

**Comment by Cookzenberg** [comment]
Thanks for the reply. That was the other documentation I found that made me realise the PDF was probably stale. 

Unfortunately following those instructions and selecting the versions specified still results in errors at runtime after the uIntra package install, e.g. 

Could not load file or assembly 'System.Diagnostics.Tracing, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 

My Visual Studio is Community Edition 15.8.6 if it has any bearing. 

There are a bunch of version-related warnings when a clean and rebuild as well that I'm looking through now.

**Comment by matsukatovv** [comment]
Ah! Yes that is the exact error Alan, had as well. This is fixed and is currently being tested for the new release, however our release strategy have been a little shaky due to vacations, we arranged with Alan that we would write to him on his email when it was ready, if you are interested in this as well, send an email to kne@compent.net and we will make sure to notify you the day it's out!

For future references I would like to mention that we are working on a new release strategy that will allow us to more flexibly deal with major bugs to avoid situations like this!

**Comment by matsukatovv** [comment]
Hi guys, We have just released Uintra version 0.5 with a fix for this problem! We have also updated the installation guide in the readme file and tested it thoroughly, I hope it will be of help to you!
