### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#114]
Version 2 Beta:

After populating several missing page titles I was finally able to get the entire site to publish.  But even after doing that, when I try and view the site I get an error:

This site can’t be reached
uintra.local’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN

I can get to the Umbraco admin just fine via uintra.local but cannot see the site.

**Comment by cdecinkoKnight** [comment]
Ok, figured this one out too.  The site is created as uintra.local instead of uintra.localhost.  Seems there is a naming mismatch in the setup?

**Comment by 1nsolenT** [comment]
Hi @cdecinkoKnight , do not use IIS Express. You need to add website to your IIS server with bindings uintra.local (do not forget about "hosts" file). After that you should add this domain "uintra.local" to root node in "Culture and Hostnames" menu at umbraco backoffice. And then you will be able to see uintra login screen. We do not use "localhost" because of some authenticate issues.
