### ISSUE TITLE
Public Pages with UIntra

### ISSUE THREAD

**Issue by jkoletar** [Uintra/Uintra#119]
We are looking to use UIntra for a portal project.  We need to have both public and password protected pages on the site.  Currently all of Uintra content is behind a password.  Is there a way to create public pages that can accessed by non-members?  Would this require a code change?  If so, could you provide some pointers as to what would need to be changed?

Thanks,
Joe

**Comment by denprodan** [comment]
Hi @jkoletar 
What version of Uintra do you use?

**Comment by jkoletar** [comment]
Hi @denprodan 
Currently using version 1.4 of Uintra and v7.15.3 of Umbraco.  We are hoping to use version 2 of Uintra once it is stable.

**Comment by denprodan** [comment]
On version 2 it wouldbe easy to do. We have AuthenticatonService with validation method where you can extend anonymous routes list
On versions 1.* you could try to open needed pages from IIS (set anonymous auth for some folders) but I can say that it will work, we never tested it because 1.* versions is for classic intranet projects where all pages are secured

**Comment by jkoletar** [comment]
Sounds like I should look into 2.0  Any updates on when Uintra 2.0.1 will be released?

**Comment by denprodan** [comment]
I really hope that release will be in this month but if not I was saying anything)
