### ISSUE TITLE
3 missing dll files with the source code.

### ISSUE THREAD

**Issue by weerapongpruchya** [Uintra/Uintra#122]
Hi,

I can't find them any where.

have a look at the attach files.

![missingdll1](https://user-images.githubusercontent.com/73492977/97211247-58d76380-17f1-11eb-90ef-e0b89648407b.png)
![missingdllfile2](https://user-images.githubusercontent.com/73492977/97211252-5bd25400-17f1-11eb-8023-5ecc2ba25dba.png)

**Comment by 1nsolenT** [comment]
Hi @weerapongpruchya  uintra.1.4.1 was not published to nuget. Please use latest version from nuget (Uintra.2.0.0). It is not possible for now to lunch source code locally for Uintra v.2.0.0+ (branch master or release/2.1) due to dependency on internal package (we are working on it).
Master branch has been updated a one hour ago, sorry for inconvenience.
