### ISSUE TITLE
Umbraco version problem

### ISSUE THREAD

**Issue by fxhst329** [Uintra/Uintra#131]
Hi,

we are considering using Uintra for our project. We upgraded our Umbraco to the latest version 8.12 and we wanted to use Uintra and got the following error

![image](https://user-images.githubusercontent.com/26558132/112312736-695c0f00-8ca7-11eb-8ed8-cd45b053fa4b.png)

From what we understand it fails because of dependencies and that they are tied to specific Umbraco version, still reffering to 8.6 

![image](https://user-images.githubusercontent.com/26558132/112312907-9c060780-8ca7-11eb-9e35-f4a1edfdeca5.png)

For example this ones

![image](https://user-images.githubusercontent.com/26558132/112313053-bd66f380-8ca7-11eb-86c0-d2867f46c89f.png)

Our concern is that we use Uintra, start developing and we will face issues with dependencies that you developed. We like to keep everything in the last versions, if there is some security fix in Umbraco that needs to fixed immediately we couldn't do so because we would be blocked by your libraries. On the other end your updating process is very slow, just if we take 8.6 - it was released like year ago.. in March 2020.

So this is major reason we worried about when choosing Uintra altough we would really like to. Is there any possible solution to this? We are willing to contribute to project and send PR's to you if it would be helpful. Is it possible to get in touch somehow?

**Comment by denprodan** [comment]
Hi @fxhst329.
Unfortunately it's not possible at this moment, because Uintra 2.* depends on Ubaseline (another internal project which wraps Umbraco) so we can consume only Umbraco version installed in Ubaseline. I hope in the future Ubaseline also became open source and you will be able to update Umbraco to needed version

**Comment by fxhst329** [comment]
Can we be a bit more constructive here? What future are we talking about? Are you considering doing it soon or it's somewhere in the end of your roadmap? Maybe you could do some commercial open source version where you would provide this library for some fee f.e. as Vendr is doing it. We don't need all your libraries just those that are crucial to updating Umbraco. Or maybe figure out better way to update Umbraco to the latest version in Uintra? We are willing to help with some developers on this if it would help the process.

**Comment by vmatsukatov** [comment]
dear @fxhst329 when we say future here, is is April - May of 2021, if we are talking about open source, free use. 

it is of course in our road map as we are striving to have everything in open source. and for commercial use, if you need that asap, just contact vma@compent.net so we will give you details, rates and terms of commercial use. we are not publishing Uintra for commercial use for now as "commercial open source version where you would provide this library for some fee" but yes, we will think about it, thank you for raising that.

**Comment by vmatsukatov** [comment]
dear @fxhst329 

UPD. About future plans for Uintra, we definitely and continuously working on it as an open source project. And yes, there are unfortunately still some functionality there, which is not open source, as only nugets only provided. 

Due to other active projects, we unfortunately not so active with Uintra new version releasing now, we of course improving it and releasing new versions continuously, but sometimes we are slower here with progress and releasing ☹.  we will annoce ETA just we have it on the official Uintra releases page https://uintra.com/releases/
