### ISSUE TITLE
uIntra on Azure

### ISSUE THREAD

**Issue by Cookzenberg** [Uintra/Uintra#14]
Hi

I saw that uIntra 1.1 had Azure support listed in the release notes (https://uintra.com/releases/). My site fires up okay when I deploy to Azure... but I don't know what version of Elasticsearch I can run in Azure that will be compatible with uIntra. 

Is it still only compatible with ES 5.2.1? 

Or can I use one of the better-supported versions? ES 5.5.3 is the earliest version I can see on the official ELK template for Azure.

Thanks
Andrew

**Comment by denprodan** [comment]
Hi Cookzenberg
Yes it is still 5.2.1
Also we provide our default elasticsearch server for uintra consumers just
for testing search
You can find link in web.config in elsdticsearch section after installing
1.1


23 дек. 2018 г. 0:08 пользователь "Cookzenberg" <notifications@github.com>
написал:

Hi

I saw that uIntra 1.1 had Azure support listed in the release notes (
https://uintra.com/releases/). My site fires up okay when I deploy to
Azure... but I don't know what version of Elasticsearch I can run in Azure
that will be compatible with uIntra.

Is it still only compatible with ES 5.2.1?

Or can I use one of the better-supported versions? ES 5.5.3 is the earliest
version I can see on the official ELK template for Azure.

Thanks
Andrew

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Uintra/Uintra/issues/14>, or mute the thread

**Comment by Cookzenberg** [comment]
Thanks. I have it all working with local uIntra and local Elasticsearch (except for the issue with the user list) but I am specifically interested in an Azure deployment. I can see if I can get ES 5.2.1 working on Azure but didn’t want to waste the time if there was an easier option using the Azure template.
