### ISSUE TITLE
Provide documentation on how to customize the colors and logo

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#20]
Provide instruction on how users can apply their own logo, change the default colors and customize the look and feel.  Changes made to postcss.config.js don't seem to have any affect.

**Comment by Cookzenberg** [comment]
Hi, are you re-running webpack after changing postcss.config.js?

**Comment by cdecinkoKnight** [comment]
Apparently Visual Studio wasn't running webpack when doing a build.  I installed WebPack Task Runner and used that.  Now I can see the changes to colors.  Is it safe to modify the layout for changing the logo?

**Comment by Cookzenberg** [comment]
That is what I have done for the login and nav views.

I maintain a copy of the modified files with a prefix so that when the originals are overwritten I can remember what I changed last time.

Denis or someone suggested there was a way of applying a custom stylesheet so I'm sure that there is an official way of doing it that I just didn't have time to nail down before I wanted to get something live.

And I'm new to both Umbraco and uIntra so don't listen to me anyway.

**Comment by denprodan** [comment]
Hi cdecinkoKnight. We are working on this part of doucumentation. We update https://docs.uintra.com/ ASAP.
