### ISSUE TITLE
Responsive Tables & Links

### ISSUE THREAD

**Issue by marceltaljaard** [Uintra/Uintra#29]
Hi there

Our company just recently deployed Uintra and as I am working through setting up pages, I've run across the below issue:

I notice that when I add a link into a table, the table breaks on Mobile and displays the <a> tag for the link along with the link name. Is there some way to fix this as it makes using tables in such a way very poor for UX on mobile?

Thank you

![unintra](https://user-images.githubusercontent.com/47443289/52463779-f9e73c00-2b80-11e9-9215-abd969b4cfb4.JPG)

**Comment by denprodan** [comment]
Hi @marceltaljaard 
Current implementation of table allows only plain text. The table is braking because you have long word (url) without spaces. 
Quick fix for you is to add in tableEditor.css => table__col=> word-break: break-word. 
And don't forget to rebuild webpack
In next release this fix will be added
