### ISSUE TITLE
Member passwords stored as clear text

### ISSUE THREAD

**Issue by cdecinkoKnight** [Uintra/Uintra#31]
This might be more of an Umbraco issue, but member/user passwords are stored in the database as clear text.

**Comment by UintraContact** [comment]
hi @cdecinkoKnight this is not something controlled by Uintra. as Uintra is on top of Umbraco, we are using be default Umbraco membership. means, you can control it in Umbraco just via configuration file

we will close this issue for now and post new, if you can see that something related is not working because of Uintra code
