### ISSUE TITLE
Access to the path 'MediaToolkit.Engine.LockName' is denied.

### ISSUE THREAD

**Issue by AllardStruiksma** [Uintra/Uintra#61]
Hello,

I installed Uintra locally and eveything seems to be working fine.
However, when I deploy it to a test server i get the following error:

Access to the path 'MediaToolkit.Engine.LockName' is denied.

I haven't been able to figure out why this error only occurs when I deploy.
Do you have any idea what could cause this error?

**Comment by denprodan** [comment]
Hi @AllardStruiksma 
Yes, this error happens when you run 2 Uintra instances on the same machine
We use https://github.com/AydinAdn/MediaToolkit for video converting and unfortunatrly it's code doesn't maintain parallel access  to the ffmpeg plugin from different processes.
To fix this error just stop AppPool for one of the instances or move it to another machine
