### ISSUE TITLE
Monthly email testing

### ISSUE THREAD

**Issue by AllardStruiksma** [Uintra/Uintra#65]
Hello,

I'm trying to test the monthly email functionality.
I haven't been able to get it to work.
Is there any way i can test this?

**Comment by denprodan** [comment]
Hi @AllardStruiksma. Sorry for late answer. If it is still actual. Could you please give us more informations? FYI monthly mail launching by job defined in Web.config=>jobs section

**Comment by AllardStruiksma** [comment]
I was wondering when a monthly email gets sent to a specific user and what content is in the email.
In the code I saw something about being subscribed to a tag so i tried  subscribing a user to a tag but i haven't been getting an email.
I found the jobs section in the web.config and tried changing some values but i couldn't get it to work. I also couldn't find anything on https://docs.uintra.com/

Is there any way i can trigger the monthly email job and send the mail to a user?

**Comment by denprodan** [comment]
Hi @AllardStruiksma 
So monthly mail will send to you if
1. You as a member add some tag f.e. "Development" on profile
2. There is any activity with the same tag ("Development") appears during last month
> Is there any way i can trigger the monthly email job and send the mail to a user?
Yes you can directly run sending via MonthlyEmailApiController =>SendMonthlyEmail
But be sure that you setup correct day for sending in web.config
 <add key="MonthlyEmailJobDay" value="12"/> value is the day of month when you want emails sending to members

> couldn't find anything on https://docs.uintra.com/
Unfortunately you can see it on demo because of fake members that we use there
